2024-03-05 14:14:15,251 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-05 14:14:15,252 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Configure stats pid to 35160
2024-03-05 14:14:15,253 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Loading settings from C:\Users\16979\.config\wandb\settings
2024-03-05 14:14:15,253 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Loading settings from G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\settings
2024-03-05 14:14:15,253 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-05 14:14:15,253 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-05 14:14:15,253 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-05 14:14:15,255 INFO    MainThread:35160 [wandb_init.py:_log_setup():526] Logging user logs to G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\run-20240305_141415-706y3no0\logs\debug.log
2024-03-05 14:14:15,256 INFO    MainThread:35160 [wandb_init.py:_log_setup():527] Logging internal logs to G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\run-20240305_141415-706y3no0\logs\debug-internal.log
2024-03-05 14:14:15,256 INFO    MainThread:35160 [wandb_init.py:init():566] calling init triggers
2024-03-05 14:14:15,256 INFO    MainThread:35160 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-05 14:14:15,256 INFO    MainThread:35160 [wandb_init.py:init():591] re-initializing run, found existing run on stack: vvfair4s
2024-03-05 14:14:15,258 INFO    MainThread:35160 [wandb_run.py:_finish():1970] finishing run yanzhuo/attention_classifier/vvfair4s
2024-03-05 14:14:15,258 INFO    MainThread:35160 [jupyter.py:save_history():445] not saving jupyter history
2024-03-05 14:14:15,258 INFO    MainThread:35160 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-05 14:14:15,259 INFO    MainThread:35160 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-03-05 14:14:15,259 INFO    MainThread:35160 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-03-05 14:14:15,260 INFO    MainThread:35160 [wandb_run.py:_restore():2193] restore
2024-03-05 14:14:15,260 INFO    MainThread:35160 [wandb_run.py:_restore():2199] restore done
2024-03-05 14:14:20,705 INFO    MainThread:35160 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-03-05 14:14:20,706 INFO    MainThread:35160 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-03-05 14:14:20,733 INFO    MainThread:35160 [wandb_run.py:_footer_sync_info():3825] logging synced files
2024-03-05 14:14:21,169 INFO    MainThread:35160 [wandb_init.py:init():616] starting backend
2024-03-05 14:14:21,169 INFO    MainThread:35160 [wandb_init.py:init():620] setting up manager
2024-03-05 14:14:21,201 INFO    MainThread:35160 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-03-05 14:14:21,201 INFO    MainThread:35160 [wandb_init.py:init():628] backend started and connected
2024-03-05 14:14:21,264 INFO    MainThread:35160 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-03-05 14:14:21,269 INFO    MainThread:35160 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'charmap' codec can't decode byte 0x81 in position 3806: character maps to <undefined>
2024-03-05 14:14:21,269 INFO    MainThread:35160 [wandb_init.py:init():720] updated telemetry
2024-03-05 14:14:21,354 INFO    MainThread:35160 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-05 14:14:22,301 INFO    MainThread:35160 [wandb_run.py:_on_init():2262] communicating current version
2024-03-05 14:14:22,678 INFO    MainThread:35160 [wandb_run.py:_on_init():2271] got version response 
2024-03-05 14:14:22,678 INFO    MainThread:35160 [wandb_init.py:init():804] starting run threads in backend
2024-03-05 14:14:22,893 INFO    MainThread:35160 [wandb_run.py:_console_start():2241] atexit reg
2024-03-05 14:14:22,893 INFO    MainThread:35160 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-03-05 14:14:22,893 INFO    MainThread:35160 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-03-05 14:14:22,898 INFO    MainThread:35160 [wandb_run.py:_redirect():2186] Redirects installed.
2024-03-05 14:14:22,904 INFO    MainThread:35160 [wandb_init.py:init():847] run started, returning control to user process
2024-03-05 14:15:59,453 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-05 14:15:59,454 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Configure stats pid to 35160
2024-03-05 14:15:59,455 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Loading settings from C:\Users\16979\.config\wandb\settings
2024-03-05 14:15:59,455 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Loading settings from G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\settings
2024-03-05 14:15:59,455 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-05 14:15:59,455 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-05 14:15:59,456 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-05 14:15:59,458 INFO    MainThread:35160 [wandb_init.py:_log_setup():526] Logging user logs to G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\run-20240305_141559-l6fpyl50\logs\debug.log
2024-03-05 14:15:59,459 INFO    MainThread:35160 [wandb_init.py:_log_setup():527] Logging internal logs to G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\run-20240305_141559-l6fpyl50\logs\debug-internal.log
2024-03-05 14:15:59,460 INFO    MainThread:35160 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001D379A107D0>
2024-03-05 14:15:59,460 INFO    MainThread:35160 [wandb_init.py:init():566] calling init triggers
2024-03-05 14:15:59,460 INFO    MainThread:35160 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-05 14:15:59,460 INFO    MainThread:35160 [wandb_init.py:init():591] re-initializing run, found existing run on stack: 706y3no0
2024-03-05 14:15:59,466 INFO    MainThread:35160 [wandb_run.py:_finish():1970] finishing run yanzhuo/attention_classifier2/706y3no0
2024-03-05 14:15:59,468 INFO    MainThread:35160 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-03-05 14:15:59,470 INFO    MainThread:35160 [wandb_run.py:_restore():2193] restore
2024-03-05 14:15:59,471 INFO    MainThread:35160 [wandb_run.py:_restore():2199] restore done
2024-03-05 14:16:04,663 INFO    MainThread:35160 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-03-05 14:16:04,664 INFO    MainThread:35160 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-03-05 14:16:04,684 INFO    MainThread:35160 [wandb_run.py:_footer_sync_info():3825] logging synced files
