2024-03-05 13:10:13,471 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-05 13:10:13,472 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Configure stats pid to 35160
2024-03-05 13:10:13,473 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Loading settings from C:\Users\16979\.config\wandb\settings
2024-03-05 13:10:13,473 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Loading settings from G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\settings
2024-03-05 13:10:13,473 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-05 13:10:13,473 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-05 13:10:13,474 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-05 13:10:13,475 INFO    MainThread:35160 [wandb_init.py:_log_setup():526] Logging user logs to G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\run-20240305_131013-8bciandm\logs\debug.log
2024-03-05 13:10:13,476 INFO    MainThread:35160 [wandb_init.py:_log_setup():527] Logging internal logs to G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\run-20240305_131013-8bciandm\logs\debug-internal.log
2024-03-05 13:10:13,477 INFO    MainThread:35160 [wandb_init.py:init():566] calling init triggers
2024-03-05 13:10:13,477 INFO    MainThread:35160 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-05 13:10:13,478 INFO    MainThread:35160 [wandb_init.py:init():591] re-initializing run, found existing run on stack: iay4cqzi
2024-03-05 13:10:13,479 INFO    MainThread:35160 [wandb_run.py:_finish():1970] finishing run yanzhuo/attention_classifier/iay4cqzi
2024-03-05 13:10:13,480 INFO    MainThread:35160 [jupyter.py:save_history():445] not saving jupyter history
2024-03-05 13:10:13,480 INFO    MainThread:35160 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-05 13:10:13,480 INFO    MainThread:35160 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-03-05 13:10:13,480 INFO    MainThread:35160 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-03-05 13:10:13,482 INFO    MainThread:35160 [wandb_run.py:_restore():2193] restore
2024-03-05 13:10:13,482 INFO    MainThread:35160 [wandb_run.py:_restore():2199] restore done
2024-03-05 13:10:18,975 INFO    MainThread:35160 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-03-05 13:10:18,976 INFO    MainThread:35160 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-03-05 13:10:18,993 INFO    MainThread:35160 [wandb_run.py:_footer_sync_info():3825] logging synced files
2024-03-05 13:10:19,478 INFO    MainThread:35160 [wandb_init.py:init():616] starting backend
2024-03-05 13:10:19,478 INFO    MainThread:35160 [wandb_init.py:init():620] setting up manager
2024-03-05 13:10:19,505 INFO    MainThread:35160 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-03-05 13:10:19,505 INFO    MainThread:35160 [wandb_init.py:init():628] backend started and connected
2024-03-05 13:10:19,557 INFO    MainThread:35160 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-03-05 13:10:19,559 INFO    MainThread:35160 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'charmap' codec can't decode byte 0x81 in position 3806: character maps to <undefined>
2024-03-05 13:10:19,559 INFO    MainThread:35160 [wandb_init.py:init():720] updated telemetry
2024-03-05 13:10:19,629 INFO    MainThread:35160 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-05 13:10:20,618 INFO    MainThread:35160 [wandb_run.py:_on_init():2262] communicating current version
2024-03-05 13:10:21,052 INFO    MainThread:35160 [wandb_run.py:_on_init():2271] got version response 
2024-03-05 13:10:21,052 INFO    MainThread:35160 [wandb_init.py:init():804] starting run threads in backend
2024-03-05 13:10:21,274 INFO    MainThread:35160 [wandb_run.py:_console_start():2241] atexit reg
2024-03-05 13:10:21,275 INFO    MainThread:35160 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-03-05 13:10:21,275 INFO    MainThread:35160 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-03-05 13:10:21,277 INFO    MainThread:35160 [wandb_run.py:_redirect():2186] Redirects installed.
2024-03-05 13:10:21,280 INFO    MainThread:35160 [wandb_init.py:init():847] run started, returning control to user process
2024-03-05 13:22:59,429 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-05 13:22:59,434 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Configure stats pid to 35160
2024-03-05 13:22:59,434 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Loading settings from C:\Users\16979\.config\wandb\settings
2024-03-05 13:22:59,435 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Loading settings from G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\settings
2024-03-05 13:22:59,435 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-05 13:22:59,435 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-05 13:22:59,435 INFO    MainThread:35160 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-05 13:22:59,437 INFO    MainThread:35160 [wandb_init.py:_log_setup():526] Logging user logs to G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\run-20240305_132259-vvfair4s\logs\debug.log
2024-03-05 13:22:59,439 INFO    MainThread:35160 [wandb_init.py:_log_setup():527] Logging internal logs to G:\My Drive\SI_630\Homeworks\Homework2 - Backup\wandb\run-20240305_132259-vvfair4s\logs\debug-internal.log
2024-03-05 13:22:59,439 INFO    MainThread:35160 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001D365B9DCD0>
2024-03-05 13:22:59,440 INFO    MainThread:35160 [wandb_init.py:init():566] calling init triggers
2024-03-05 13:22:59,440 INFO    MainThread:35160 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-05 13:22:59,440 INFO    MainThread:35160 [wandb_init.py:init():591] re-initializing run, found existing run on stack: 8bciandm
2024-03-05 13:22:59,442 INFO    MainThread:35160 [wandb_run.py:_finish():1970] finishing run yanzhuo/attention_classifier2/8bciandm
2024-03-05 13:22:59,442 INFO    MainThread:35160 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-03-05 13:22:59,444 INFO    MainThread:35160 [wandb_run.py:_restore():2193] restore
2024-03-05 13:22:59,444 INFO    MainThread:35160 [wandb_run.py:_restore():2199] restore done
2024-03-05 13:23:04,753 INFO    MainThread:35160 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-03-05 13:23:04,753 INFO    MainThread:35160 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-03-05 13:23:04,774 INFO    MainThread:35160 [wandb_run.py:_footer_sync_info():3825] logging synced files
