2024-03-02 06:57:43,723 INFO    MainThread:2756 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-02 06:57:43,739 INFO    MainThread:2756 [wandb_setup.py:_flush():76] Configure stats pid to 2756
2024-03-02 06:57:43,739 INFO    MainThread:2756 [wandb_setup.py:_flush():76] Loading settings from C:\Users\16979\.config\wandb\settings
2024-03-02 06:57:43,739 INFO    MainThread:2756 [wandb_setup.py:_flush():76] Loading settings from G:\Œ“µƒ‘∆∂À”≤≈Ã\SI_630\Homeworks\Homework2\wandb\settings
2024-03-02 06:57:43,739 INFO    MainThread:2756 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-02 06:57:43,739 INFO    MainThread:2756 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-02 06:57:43,739 INFO    MainThread:2756 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-02 06:57:43,739 INFO    MainThread:2756 [wandb_init.py:_log_setup():526] Logging user logs to G:\Œ“µƒ‘∆∂À”≤≈Ã\SI_630\Homeworks\Homework2\wandb\run-20240302_065743-4ouygc9s\logs\debug.log
2024-03-02 06:57:43,739 INFO    MainThread:2756 [wandb_init.py:_log_setup():527] Logging internal logs to G:\Œ“µƒ‘∆∂À”≤≈Ã\SI_630\Homeworks\Homework2\wandb\run-20240302_065743-4ouygc9s\logs\debug-internal.log
2024-03-02 06:57:43,739 INFO    MainThread:2756 [wandb_init.py:init():566] calling init triggers
2024-03-02 06:57:43,739 INFO    MainThread:2756 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-02 06:57:43,739 INFO    MainThread:2756 [wandb_init.py:init():591] re-initializing run, found existing run on stack: zcvd2t70
2024-03-02 06:57:43,750 INFO    MainThread:2756 [wandb_run.py:_finish():1970] finishing run yanzhuo/attention_classifier/zcvd2t70
2024-03-02 06:57:43,750 INFO    MainThread:2756 [jupyter.py:save_history():445] not saving jupyter history
2024-03-02 06:57:43,750 INFO    MainThread:2756 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-02 06:57:43,750 INFO    MainThread:2756 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-03-02 06:57:43,750 INFO    MainThread:2756 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-03-02 06:57:43,755 INFO    MainThread:2756 [wandb_run.py:_restore():2193] restore
2024-03-02 06:57:43,755 INFO    MainThread:2756 [wandb_run.py:_restore():2199] restore done
2024-03-02 06:58:13,005 INFO    MainThread:2756 [wandb_init.py:init():616] starting backend
2024-03-02 06:58:13,005 INFO    MainThread:2756 [wandb_init.py:init():620] setting up manager
2024-03-02 06:58:13,046 INFO    MainThread:2756 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-03-02 06:58:13,046 INFO    MainThread:2756 [wandb_init.py:init():628] backend started and connected
2024-03-02 06:58:13,130 INFO    MainThread:2756 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-03-02 06:58:13,145 INFO    MainThread:2756 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'gbk' codec can't decode byte 0xae in position 3812: illegal multibyte sequence
2024-03-02 06:58:13,145 INFO    MainThread:2756 [wandb_init.py:init():720] updated telemetry
2024-03-02 06:58:13,274 INFO    MainThread:2756 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-02 06:58:25,359 WARNING MainThread:2756 [wandb_init.py:init():1198] interrupted
Traceback (most recent call last):
  File "D:\Pycharm\Lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "D:\Pycharm\Lib\site-packages\wandb\sdk\wandb_init.py", line 756, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Pycharm\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Pycharm\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Pycharm\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Pycharm\Lib\threading.py", line 622, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Pycharm\Lib\threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-03-02 06:58:26,232 WARNING MsgRouterThr:2756 [router.py:message_loop():77] message_loop has been closed
2024-03-02 06:58:26,232 WARNING MsgRouterThr:2756 [router.py:message_loop():77] message_loop has been closed
