2024-03-03 06:52:59,563 INFO    MainThread:5616 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-03 06:52:59,574 INFO    MainThread:5616 [wandb_setup.py:_flush():76] Configure stats pid to 5616
2024-03-03 06:52:59,574 INFO    MainThread:5616 [wandb_setup.py:_flush():76] Loading settings from C:\Users\16979\.config\wandb\settings
2024-03-03 06:52:59,574 INFO    MainThread:5616 [wandb_setup.py:_flush():76] Loading settings from G:\Œ“µƒ‘∆∂À”≤≈Ã\SI_630\Homeworks\Homework2\wandb\settings
2024-03-03 06:52:59,574 INFO    MainThread:5616 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-03 06:52:59,574 INFO    MainThread:5616 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-03 06:52:59,574 INFO    MainThread:5616 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-03 06:52:59,574 INFO    MainThread:5616 [wandb_init.py:_log_setup():526] Logging user logs to G:\Œ“µƒ‘∆∂À”≤≈Ã\SI_630\Homeworks\Homework2\wandb\run-20240303_065259-8rlfagwn\logs\debug.log
2024-03-03 06:52:59,574 INFO    MainThread:5616 [wandb_init.py:_log_setup():527] Logging internal logs to G:\Œ“µƒ‘∆∂À”≤≈Ã\SI_630\Homeworks\Homework2\wandb\run-20240303_065259-8rlfagwn\logs\debug-internal.log
2024-03-03 06:52:59,574 INFO    MainThread:5616 [wandb_init.py:init():566] calling init triggers
2024-03-03 06:52:59,574 INFO    MainThread:5616 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-03 06:52:59,574 INFO    MainThread:5616 [wandb_init.py:init():591] re-initializing run, found existing run on stack: 1n5uv0ns
2024-03-03 06:52:59,574 INFO    MainThread:5616 [wandb_run.py:_finish():1970] finishing run yanzhuo/attention_classifier/1n5uv0ns
2024-03-03 06:52:59,574 INFO    MainThread:5616 [jupyter.py:save_history():445] not saving jupyter history
2024-03-03 06:52:59,574 INFO    MainThread:5616 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-03 06:52:59,574 INFO    MainThread:5616 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-03-03 06:52:59,574 INFO    MainThread:5616 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-03-03 06:52:59,589 INFO    MainThread:5616 [wandb_run.py:_restore():2193] restore
2024-03-03 06:52:59,589 INFO    MainThread:5616 [wandb_run.py:_restore():2199] restore done
2024-03-03 06:53:05,588 INFO    MainThread:5616 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-03-03 06:53:05,588 INFO    MainThread:5616 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-03-03 06:53:05,622 INFO    MainThread:5616 [wandb_run.py:_footer_sync_info():3825] logging synced files
2024-03-03 06:53:06,105 INFO    MainThread:5616 [wandb_init.py:init():616] starting backend
2024-03-03 06:53:06,105 INFO    MainThread:5616 [wandb_init.py:init():620] setting up manager
2024-03-03 06:53:06,167 INFO    MainThread:5616 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-03-03 06:53:06,168 INFO    MainThread:5616 [wandb_init.py:init():628] backend started and connected
2024-03-03 06:53:06,255 INFO    MainThread:5616 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-03-03 06:53:06,255 INFO    MainThread:5616 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'gbk' codec can't decode byte 0xae in position 3807: illegal multibyte sequence
2024-03-03 06:53:06,255 INFO    MainThread:5616 [wandb_init.py:init():720] updated telemetry
2024-03-03 06:53:06,606 INFO    MainThread:5616 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-03 06:53:07,239 INFO    MainThread:5616 [wandb_run.py:_on_init():2262] communicating current version
2024-03-03 06:53:07,639 INFO    MainThread:5616 [wandb_run.py:_on_init():2271] got version response 
2024-03-03 06:53:07,639 INFO    MainThread:5616 [wandb_init.py:init():804] starting run threads in backend
2024-03-03 06:53:08,861 INFO    MainThread:5616 [wandb_run.py:_console_start():2241] atexit reg
2024-03-03 06:53:08,861 INFO    MainThread:5616 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-03-03 06:53:08,861 INFO    MainThread:5616 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-03-03 06:53:08,876 INFO    MainThread:5616 [wandb_run.py:_redirect():2186] Redirects installed.
2024-03-03 06:53:08,876 INFO    MainThread:5616 [wandb_init.py:init():847] run started, returning control to user process
2024-03-03 06:54:11,540 INFO    MainThread:5616 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-03 06:54:11,556 INFO    MainThread:5616 [wandb_setup.py:_flush():76] Configure stats pid to 5616
2024-03-03 06:54:11,556 INFO    MainThread:5616 [wandb_setup.py:_flush():76] Loading settings from C:\Users\16979\.config\wandb\settings
2024-03-03 06:54:11,556 INFO    MainThread:5616 [wandb_setup.py:_flush():76] Loading settings from G:\Œ“µƒ‘∆∂À”≤≈Ã\SI_630\Homeworks\Homework2\wandb\settings
2024-03-03 06:54:11,556 INFO    MainThread:5616 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-03 06:54:11,556 INFO    MainThread:5616 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-03 06:54:11,556 INFO    MainThread:5616 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-03 06:54:11,556 INFO    MainThread:5616 [wandb_init.py:_log_setup():526] Logging user logs to G:\Œ“µƒ‘∆∂À”≤≈Ã\SI_630\Homeworks\Homework2\wandb\run-20240303_065411-va1rkigu\logs\debug.log
2024-03-03 06:54:11,556 INFO    MainThread:5616 [wandb_init.py:_log_setup():527] Logging internal logs to G:\Œ“µƒ‘∆∂À”≤≈Ã\SI_630\Homeworks\Homework2\wandb\run-20240303_065411-va1rkigu\logs\debug-internal.log
2024-03-03 06:54:11,556 INFO    MainThread:5616 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001BE5F1C09D0>
2024-03-03 06:54:11,556 INFO    MainThread:5616 [wandb_init.py:init():566] calling init triggers
2024-03-03 06:54:11,556 INFO    MainThread:5616 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-03 06:54:11,556 INFO    MainThread:5616 [wandb_init.py:init():591] re-initializing run, found existing run on stack: 8rlfagwn
2024-03-03 06:54:11,556 INFO    MainThread:5616 [wandb_run.py:_finish():1970] finishing run yanzhuo/attention_classifier2/8rlfagwn
2024-03-03 06:54:11,569 INFO    MainThread:5616 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-03-03 06:54:11,572 INFO    MainThread:5616 [wandb_run.py:_restore():2193] restore
2024-03-03 06:54:11,572 INFO    MainThread:5616 [wandb_run.py:_restore():2199] restore done
2024-03-03 06:54:17,641 INFO    MainThread:5616 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-03-03 06:54:17,642 INFO    MainThread:5616 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-03-03 06:54:17,679 INFO    MainThread:5616 [wandb_run.py:_footer_sync_info():3825] logging synced files
